// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVdT2MR_7nPUT50Nl8P3xtnEfGFDqNqqg',
    appId: '1:616671132787:web:7f4a6a7bfd10e0486c3e06',
    messagingSenderId: '616671132787',
    projectId: 'collaborative-notes-demo',
    authDomain: 'collaborative-notes-demo.firebaseapp.com',
    storageBucket: 'collaborative-notes-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6aywjqB6aoJVohveqOytVBA9h4SItTs0',
    appId: '1:616671132787:android:f738721da2b1eb746c3e06',
    messagingSenderId: '616671132787',
    projectId: 'collaborative-notes-demo',
    storageBucket: 'collaborative-notes-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_F37bnQmDKvC1jJCSdF99M3HwoDoZ79M',
    appId: '1:616671132787:ios:57aa4f7a9f57ed936c3e06',
    messagingSenderId: '616671132787',
    projectId: 'collaborative-notes-demo',
    storageBucket: 'collaborative-notes-demo.firebasestorage.app',
    iosBundleId: 'com.example.collaborativeNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_F37bnQmDKvC1jJCSdF99M3HwoDoZ79M',
    appId: '1:616671132787:ios:57aa4f7a9f57ed936c3e06',
    messagingSenderId: '616671132787',
    projectId: 'collaborative-notes-demo',
    storageBucket: 'collaborative-notes-demo.firebasestorage.app',
    iosBundleId: 'com.example.collaborativeNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVdT2MR_7nPUT50Nl8P3xtnEfGFDqNqqg',
    appId: '1:616671132787:web:dc241cebf0544f4d6c3e06',
    messagingSenderId: '616671132787',
    projectId: 'collaborative-notes-demo',
    authDomain: 'collaborative-notes-demo.firebaseapp.com',
    storageBucket: 'collaborative-notes-demo.firebasestorage.app',
  );

}